[phases.setup]
nixPkgs = ['nodejs_20']

[phases.install]
cmds = ['npm install', 'cd ../FastBuss-Admin && npm install']

[phases.build]
cmds = ['cd ../FastBuss-Admin && npm run build', 'npm run build']

[start]
cmd = 'npm run start'
